- name: demo ansible mysql db
  hosts: mysql
  become: true
  tasks:
    - name: install mysql connecter and mysql client and server
      package:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: true
    
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: true

    - name: creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating db
      mysql_db:
        name: "{{db_name}}"
        state: present

    - name: enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
  
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted








