- name: ansible prometheus demo
  hosts: prometheus
  become: true
  tasks:
    - name: update and install prometheus
      apt:
        name: prometheus
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: prometheus args
      template:
        src: prometheus.j2
        dest: /etc/default/prometheus
        mode: 0644
        owner: root
        group: root
      notify: restart_prometheus

    - name: prometheus configuration file
      template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
        mode: 0755
        owner: prometheus
        group: prometheus
      notify: 
        - reload_prometheus

    - name: start prometheus
      service:
        name: prometheus
        state: started
        enabled: yes

  handlers:
    - name: restart_prometheus
      service:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: reload_prometheus
      uri:
        url: http://localhost:9090/-/reload
        method: POST
        status_code: 200
